# DS - Daily Shells Library
# License:
#  See README.md document in projects page at
#  https://github.com/stroparo/ds

alias agas='ag --asm'
alias agbat='ag --batch'
alias agcc='ag --cc'
alias agcl='ag --clojure'
alias agcpp='ag --cpp'
alias agcs='ag --csharp'
alias agcss='ag --css'
alias agd='ag --delphi'
alias agel='ag --elixir'
alias ager='ag --erlang'
alias agh='ag --html'
alias agj='ag --js'
alias agm='ag --md -i'
alias agmk='ag --mk -i'
alias agp='ag --php'
alias agr='ag --ruby'
alias agrs='ag --rust'
alias ags='ag --shell'
alias agsa='ag --sass'
alias agsc='ag --scala'
alias agsq='ag --sql'
alias agv='ag --vim'
alias agy='ag --python'
alias agym='ag --yaml'
alias agx='ag --xml'
