#!/usr/bin/env bash

# Script to save disk using ocs, the program used by clonezilla linux distro.

# Additional info:
# 2nd arg is backup prefix override (default is 'ocs').

if [ -z "$1" ] ; then
  echo "Must pass device to be saved (sd?)."
  exit 1
fi

/usr/sbin/ocs-sr -q2 -j2 -rm-win-swap-hib -z1p -i 4096 -gm -sc -p true \
    savedisk "${2:-ocs}"-"$(date '+%Y%m%d-%OH%OM')" "$1"
echo $?
