#!/usr/bin/env bash

# Script to restore disk using ocs, the program used by clonezilla linux distro.

# Syntax (TODO confirm): {image} {destination}

[ -z "${1}" -o -z "$2" ] && exit 1

/usr/sbin/ocs-sr -g auto -e1 auto -e2 -c -r -j2 -p true \
    restoredisk "${1}" "${2}"
echo $?
