#!/usr/bin/env bash

# Project / License at https://github.com/stroparo/ds

PROGNAME="dotfiles"

export DOTFILES_SELECTS="${DOTFILES_SELECTS} alias dotfiles git sshmodes vim"

echo
echo "${PROGNAME:+$PROGNAME: }INFO: Executing dotfiles selects..." 1>&2
echo "${DOTFILES_SELECTS}"
echo "${PROGNAME:+$PROGNAME: }INFO: Started..."
runrhash.sh ${DOTFILES_SELECTS}

echo "${PROGNAME:+$PROGNAME: }INFO: COMPLETE" 1>&2
