#!/usr/bin/env bash

# Install Everpad in Ubuntu

# ##############################################################################
# Dependencies

# Enforce Operating System
if ! grep -q Ubuntu /etc/os-release ; then
    echo 'SKIP: Not in Ubuntu' 1>&2
    exit
fi

# Daily Shells
! . ~/.ds/ds.sh && echo "FATAL: sourcing daily shells" && exit 1
[ -n "$DS_LOADED" ] || exit $?

# APT
export APTPROG=apt-get
if which apt >/dev/null 2>&1 ; then
    export APTPROG=apt
fi

# ##############################################################################

aptaddppa 'nvbn-rm/ppa'
sudo $APTPROG update || return $?
sudo $APTPROG install -y everpad || return $?

